### ISSUE TITLE
favicon.icoがほしい

### ISSUE THREAD

**Issue by kkd** [cheerup-ehime/cheerup-ehime.github.io#11]
@brightflavor さん、作ってくれるとありがたい。

**Comment by brightflavor** [comment]
ファビコンくらいでしたら何とか。
マーク何にしましょう？

**Comment by brightflavor** [comment]
安直だけど『救急戦隊ゴーゴーファイブ』が浮かんだ…。

**Comment by kkd** [comment]
6809f57387b047069d58b08799749ab58b8aaaef 似て対応。

**Comment by kkd** [comment]
@brightflavor ありがとー。

**Comment by brightflavor** [comment]
@kkd 
あ、ありがとうございます。UPしたのはいいけど、タグの入れ先ががわからんかったので助かりました。
