### ISSUE TITLE
被災地支援者としてふるさと納税の義援金の自治体毎の寄付金額合計をビジュアルに見たい

### ISSUE THREAD

**Issue by kkd** [cheerup-ehime/cheerup-ehime.github.io#53]
## 誰のために？

被災地を義援金で支援したい人のために

## 何を実現したい？

ふるさと納税の義援金を自治体毎にいくらになっているかを取得して記事化・グラフ化したい。
そのために、ふるさと納税のサイトをスクレイピングして定時取得し合計し、グラフ化する。

## それはなぜ？

金額だけだとピンとこないのと、代理寄付もあり、ある自治体の合計金額が見えない。
被害規模に対して、どれくらい集まっているのか、そうでないのかが見えない。

## どうなったら完了？

- [-] ふるさと納税サイトからデータが収集できCSVに出力できている
- [-] CSVを読み込み、自治体ごとの小計ができている
- [-] データの日次毎の金額の推移を記録してCSVに出力できている
- [x] 自治体ごとに時系列毎のグラフ出力(Y軸金額、X軸日時）ができている
- [x] 自治体ごとに義援金の合計がグラフ化できている
- [-] Markdownの義援金ページを作成し、グラフを表示できている
  - [-] _pages/donation_analysis.md

**Comment by imabari** [comment]
ふるさとチョイス災害支援から日付・被災地・代理・金額・件数をスクレイピング
https://imabari.hateblo.jp/entry/2018/08/02/235820

**Comment by imabari** [comment]
スプレッドシートで最新情報を取得して集計とグラフ表示しています
https://docs.google.com/spreadsheets/d/1eaIw6CyRkdFgL_i_Z6NglyHUvUkK-Zp1FJ2dzQidIig/edit?usp=sharing

**Comment by imabari** [comment]
<iframe width="600" height="371" seamless frameborder="0" scrolling="no" src="https://docs.google.com/spreadsheets/d/e/2PACX-1vR_CFMptnG-5lgZQ7P0UepPod3OerN3VWFAeXb0YgZGg73PijhLkWDxAIWRwOBM8kmWxP7ubxnedkj1/pubchart?oid=825022101&amp;format=interactive"></iframe>
これを埋め込んでもらうとグラフ表示されます。

**Comment by kkd** [comment]
ありがとうございます！

**Comment by kkd** [comment]
こちらで一旦クローズ。https://github.com/cheerup-ehime/cheerup-ehime.github.io/commit/41bd72dc13e888f9f57f0641085e5850d3dbf662

ただしスマホだと表示が切れてしまう（画像のサイズが固定のため）
