### ISSUE TITLE
松山を拠点にしてボラバスを使ったボランティア旅行を記事化したい

### ISSUE THREAD

**Issue by kkd** [cheerup-ehime/cheerup-ehime.github.io#55]
## 誰のために？

県外からボランティアに行こうとする学生、社会人向け

## 何を実現したい？

松山市から宇和島へボランティアバスが出ている。しかし現在は松山市民が使うイメージしかない。しかしその実態は、被災地には宿泊できないが、松山に滞在しながらボランティアに通う見学ボランティアの方々のためにある側面が強い。

社協でアピールできていないので、そこをアピールする記事を描きたい。

そのためには、

- 松山の滞在地（低価格のゲストハウス）
- ボランティアに必要な手続きや準備物
  - 購入できる場所、松山市内の地図
- 松山や周辺の観光スポット

などの情報がセットで準備されている必要がある。

## それはなぜ？

県外から来た人は地理に不案内だし、車もなく、店もわからない。そういった人の視点にたつ情報集約が必要。

## どうなったら完了？

- 県外の人がみて迷わないフローになっていること。
- 実際に記事の順番で手続きをすれば他の情報を参照せずに実現できること。

**Comment by shokotakaichi** [comment]
「ボランティアと観光をセットに」というのが魅力的に思い、“車でボランティアに来てちょっと愛媛をまわってみる”人にとって愛媛にしかないものや光景をピックアップしてツイッターに流しています。
https://twitter.com/AlivefactoryP/status/1025222433177919488
・ちょっと寄れる場所にしぼっています（ボランティアで疲れているでしょうし）
・なるべく全国でもめずらしいものにしています。
・学生、社会人を意識しています（家族むけではない）
・「愛媛へ来てね、魅力的だよ」という発信なのですが、現実のボランティア活動とのギャップを感じ、もう少し現実的な内容も取り込まないといけないなと感じています（実際にボランティアに参加して申請書類の作成や準備物についても触れたい）。

他アカウントでリツイートして、一番多いもののインプレッションは5000・エンゲージメント総数450です。「ボランティアにきて、そのついでに愛媛を楽しんでほしい」というコンセプトで東予の観光地も載せていこうかと思っています。わずかながら愛媛のことをツイッターで目にしてもらえればと思い。

**Comment by kkd** [comment]
をを、これいいですね！Twitterのまとめをチアで記事化してみてはどうでしょう？
問題はボラバスがいつまで続くかなんですが。。。。

ボラで疲れた体にとってボラバスはすごい楽なので
お盆明けもボラバスを延長してもらえるなにかが必要かもしれません。。。

**Comment by shokotakaichi** [comment]
“Twitterのまとめをチアで記事化”のやり方がちょっとわからないです…すみません…！
「愛媛でみられる珍しい場所(もの)」シリーズ、続けますね＾＾

**Comment by kkd** [comment]
@shokotakaichi 

Twitterでまとめたものを、note.muで記事として書いて頂ければ、それをチアからリンクしたり、その内容をこっちにも転載するなどできるかな？と思いました。

**Comment by kkd** [comment]
ボラバスの運営が未定なので一旦クローズする。
