### ISSUE TITLE
吉田町の地区が区分けされた地図と、その状況を可視化したい

### ISSUE THREAD

**Issue by kkd** [cheerup-ehime/cheerup-ehime.github.io#58]
## 誰のために？

被災地で活動している人、ボランティアに行きたい人

## 何を実現したい？
吉田町の地図と、その地区名、どこがどんな支援が必要かを可視化したい。その上で、それぞれのエリアで活動しているボランティアグループと連携して、ボラ募集や支援要請を外部に発信したい。そのための地図をまず作りたい

エリア毎の名前と境界がわかり、それぞれの被害状況や必要なものがみえるような地図

![](http://www.ehime-sci.jp/42yoshida/jpg/42.gif)

エリア毎にこんな感じで色分けされているといい（ @yamada1231 さん作の例）

![image](https://user-images.githubusercontent.com/37254/43630333-f4ca0660-973a-11e8-9c7b-453f06dcf26f.png)

## それはなぜ？
吉田町といってもエリアが広く、ボランティアの数の濃淡があり、支援が欲しくても人が来ないところが多い。玉津、立間は人が来ているが、南部はまだ人手がたりていない。それにもかかわらず、宇和島市が支援の縮小を言っていて、現実と乖離している。

吉田町内のボランティアの全体最適化を行いたい。

## どうなったら完了？

- 吉田町の地区名（被害があるところ）、そのエリアが見える地図ができている
- 各地区の状況が表現されている（地図上でなくても別途テキストでもいい）
- 地区ごとのボランティアグループの連絡先が表示されている

**Comment by daichancorgi** [comment]
すみません、そのどこでどういった状況という可視化のネタは誰が把握してる感じなんでしょうか？
- 拠点となるグループ？（だけど、そこのグループでは対応してないってことですよね。でもネタは持ってるってこと？）
- 被災者自体？

ボランティアに行きたい人...は個人だと、すでに拠点貼ってる所（ボラセン含め）に連絡するんですよね。

どこも団体がついてない地域に来てもらうんだけど、
そのネタは被災者自身しか持ってないという感じ？

大雑把に状況を入れた地図が作りたい感じなんでしょうか？
一応、みん地図は拠点ごとにデータ表示するようにしてます。
多分、見やすいという所まではいかないけど。

**Comment by kkd** [comment]
> すみません、そのどこでどういった状況という可視化のネタは誰が把握してる感じなんでしょうか？
> 拠点となるグループ？（だけど、そこのグループでは対応してないってことですよね。でもネタは持ってるってこと？）
> 被災者自体？

各地区でVCとは別に独立して（もしくは連携して）活動されている方々がいらっしゃいます。
一方で、ボランティア募集をFB通じて募ってるのに集まっていない地区もあります。
VCから見離されている、という意見もききます（実際はわかりません）

目的は、エリアごとの状況と支援の濃淡を見える化して、手付かずのところに人を送り込むこと。
そのための第一歩かなと思ってます。
ある意味、VCが手一杯なので回ってない状況をカイゼンする方法と位置づけてます。

こちらも活動グループ全部把握しているわけではないので、まず知ってる状況でたたきを作って、拡散して情報を集める＆発信するを同時並行でやるイメージです。

まず地名だけだとピンとこないですからね＞吉田町の各地区

**Comment by kkd** [comment]
キーマンはこちら参照

https://github.com/cheerup-ehime/cheerup-ehime.github.io/wiki/KeymanOnFacebook

**Comment by kkd** [comment]
宇和島の防災マップは参考になる？

https://www.city.uwajima.ehime.jp/soshiki/5/bousai-map.html

**Comment by daichancorgi** [comment]
VCとの話になると、ちょっと気になるんですが。

災害VCは生活再建くらいしかしないですよね。
そのVCに見放されている（と思われている）のは、みかん山だったりしないんですかね？
VCに言っても、そもそもケア対象外（じゃないのかな？）。
双方の言い分聞きたいけど。

みかん山の事になるんだったら
当事者にとっては、NPOとか産業に関してもケアしてくれるところに見つけてもらうしかない。
大規模崩落であれば、個人ボラが対処できるかもわからない。
プロボノが必要なケースの方が多いような気がします。
FBでの呼びかけに対して、個人でいくのは、縁者しかいないんじゃないですか。
普通は、私みたいな個人ボラは団体の拠点（VC、NPO団体など）にいくと思うので。

それ以外のケースで、VCが見放しているケースとしたら、
家の持ち主が入院とかの理由で、家を離れているとかで、そもそも依頼が出せてないケースとかですかね。

**Comment by yamada1231** [comment]
吉田町がVC求めてるのは、ミカン山ではないですね。
基本的には土砂災害による住居内土砂出しや生活空間の確保の話。

道の確保が遅れたのと、宇和島市の初動の遅れから、大洲、野村のフェーズより遅れて、いままさにまだ生活再建の部分です。VCに見放されてるのではなくて、ボランティアの維持が駐車場や宿の絶対数を確保出来ないことから、全国ボランティアを受け入れられなくなった。って話です。

もちろん、VCが吉田の地理、地域を把握できなくて、結果見捨てられてるって感じてる状態。もしくは土砂崩れの場所がピンポイントに数多の場所で発生してるため、それらに対する位置の指示も曖昧にならざるえない状況があったのではないかと思います。

あとご指摘のとおり、家の持ち主が不在でそもそも依頼もないし、手を出せない、片付けられない場所が街中にも点在していて、そこは手つかずの模様。これも次のフェーズで問題になってくるでしょうね。

ミカン山は重機入れないとVCで対処できるレベルじゃないですもんね。。。

**Comment by kkd** [comment]
立間でボラグループを作って、実際に回してる方の話を聞いたのですが

- そのエリアの自治会と連携する
- 社協に相談して、社協認定グループとしてもらうことで県外ボラを呼べるようにした

**Comment by kkd** [comment]
> VCに見放されてるのではなくて、ボランティアの維持が駐車場や宿の絶対数を確保出来ないことから、全国ボランティアを受け入れられなくなった。って話です。

#55 と連動して、松山から人を送り込むことを県外にアピールしたい（が、四国限定制約ががが！！）

**Comment by daichancorgi** [comment]
別に四国限定でもいいと思うんですが。
だって、広島も岡山も被災してるから、VCもそちらに配慮して、四国内に限定していってる側面もあると思うんです。

四国に限定的にしたからといって、別に見捨ててないし。
（松山の人間はもっとボラに行け（心の声））
総数的には細めて行くけど、長期的にやって行くんだと思うんです。

**Comment by kkd** [comment]
「限定をする必要性」がない、ということですよー。

実際、県外から行きたいといってるけど、近隣に宿泊施設がなくて行けないという人もいますし。
県外から行きたいと言ってもらってるが、受け入れられなくてごめんなさい、と誤ってる方のFB投稿もあります。（シェア控えてるのでここには貼りませんが）

ここの[VCのリスト](https://www.saigaivc.com/%E5%B9%B3%E6%88%9030%E5%B9%B47%E6%9C%88%E8%B1%AA%E9%9B%A8%E7%81%BD%E5%AE%B3/)でみても◎でエリア限定しているところないみたいです。

松山に宿とって滞在→ボラバスで日帰りボラ
というスタンスで観光＋ボラというスタイルができるはずなのに、四国限定だとできない。（個人は）

一つアイデアとしては、**ボラしたい個人を集めて、一つの団体（任意団体）として、送り込む**という技でいけるのかもしれない。その場合でも団体でどう現地でいくのか？という問題はありますが。

松山社協の方にも、ボラバスを県外向けにアピールしてない（＝市内の人言ってくれに見える）ので、そのアイデアはいいですねというフィードバックはもらってます。

**Comment by daichancorgi** [comment]
四国の事だから、まずは四国でまかなうのは前提だと思うので、「限定してもいい」と思ってます。
もっと来て欲しいだろうけど、他の被災地もあり結局は取り合い。

ボラバス県外からの人もいましたよ。大阪、気仙沼。
大阪の女性は青春18切符で来て、連チャンでした。
kkdさんが言われている、松山宿泊して現地へバスへ行ってるケースですよね。
ボラバスは一応12日までだけど、その後はどうするかまた検討するんだと思います。
なので、県外向けにはボラバス活用の提案はいいんじゃないですか？
行き先の宇和島VCのFBでは、
> 団体（ボランティアバス）は『全国』とさせていただきます。

とあるし。

四国でまずはボラという水脈を掘り起こすのが先なんじゃないかと思うんですが。
もう掘り尽くしたんですかね？
私が知らないだけとは思うけど、私の周りにボラに行ってる人は残念ながらほとんどいないんですよね。
限りなくゼロです。
災害発生当初に行動した人はいたけど、それで終わってる。

県外から来てもらうのって、日帰りもできない、ガソリンも高速代も時間もかかる。
だったら、近くの人が行く方がそもそも効率がいい。

すみません、だいぶズレて来たので、これで終わりにします。

**Comment by kkd** [comment]
> すみません、だいぶズレて来たので、これで終わりにします。
FBページでも似たような[コメント](https://www.facebook.com/uwajimasvc/posts/287623608654102)がたくさんついてます。
この件（四国限定の是非）は一旦終わりにしましょう。

いろいろな理由があるにせよ、現状を考えた時に何を一番優先しないといけないのか、その理由はなぜか、意志決定の理由を表明しないまま、最終決定のみを公開することで、様々な憶測が飛び交い、不信感が生まれるという、**意志決定の透明性の欠如**の典型例だと感じます。

この決断により現場の士気がこれ以上下がらないこと、悪い方向に行かないことを祈るばかりです。

**Comment by kkd** [comment]
@yamada1231 さんの情報

![image](https://user-images.githubusercontent.com/37254/43672820-d1c093e4-97f0-11e8-9d13-74dcb8006943.png)

> やはり、エリア分けは予想通り小学校エリア別で呼称してますね。
> エリアとしては玉津（たまつ）、立間（たちま）、喜佐方（きさかた）、吉田（よしだ）、奥南（おくな）の5地区になります。

**Comment by shokotakaichi** [comment]
![-01](https://user-images.githubusercontent.com/41728735/43676852-be08eb24-9833-11e8-93a7-15761c7fe38a.png)
![-03](https://user-images.githubusercontent.com/41728735/43676854-c422f05e-9833-11e8-9715-c4670f550df1.png)
![-04](https://user-images.githubusercontent.com/41728735/43676855-c818fd70-9833-11e8-9ce2-43bc362226f6.png)
![-05](https://user-images.githubusercontent.com/41728735/43676858-ca82bfce-9833-11e8-8d74-acc8e8c7a0e0.png)
![-06](https://user-images.githubusercontent.com/41728735/43676860-d2fb880c-9833-11e8-917a-0e4e5d391de8.png)

**Comment by shokotakaichi** [comment]
シンプルな地図を作りました。
aiデータはこちらです。
https://drive.google.com/open?id=1-EyjjinNwQmKdlUajlnKgR2VK4uc7cbW

**Comment by kkd** [comment]
@shokotakaichi 素敵な地図ありがとうございます！

一番最後の被害の区分けの図、凡例付けてもらえませんでしょうか？

**Comment by kkd** [comment]
@shokotakaichi 私はaiないのでデータあっても何もできなかったりｗ

**Comment by shokotakaichi** [comment]
![180805map-01](https://user-images.githubusercontent.com/41728735/43690468-86788832-9945-11e8-9714-8eed75a6f6c4.png)
![180805map-02](https://user-images.githubusercontent.com/41728735/43690469-86a11fa4-9945-11e8-9d75-c0c10abfa7aa.png)
![180805map-03](https://user-images.githubusercontent.com/41728735/43690470-86cafad6-9945-11e8-9958-24b7ce3de242.png)


断然googleマップの方が拡大縮小できるのでわかりやすのですが、宇和島朝日ICのある地図作成しました。駐車場地図も。
あると便利かもしれないと思い。
愛媛県の市町村区切りのないものも。（吉田の位置をわかりやすくするため）

**Comment by kkd** [comment]
@ https://github.com/cheerup-ehime/cheerup-ehime.github.io/commit/3436f855eaa300fa5aea6682532e51f937c9f642 で対応した。close.
