### ISSUE TITLE
ふるさと納税の義援金集計をスマホでもグラフで切れないようにみたい

### ISSUE THREAD

**Issue by kkd** [cheerup-ehime/cheerup-ehime.github.io#64]
## 誰のために？

寄付を考えている人

## 何を実現したい？

現状は #53 で対応したグラフは、Google Spread Sheetの出力したグラフをiframeで表示しているが、グラフサイズが固定のため、スマホの画面サイズでは切れてしまう（iPhone8は375px）

スマホでも見きれないようにしたい。

## それはなぜ？

スマホでのアクセスが多く、スマホメインにしたいため。

## どうなったら完了？

- [ ] スマホの画面でグラフが切れないようにみれること
  - とりあえずは固定サイズでも構わない。可変ならなお良い。

**Comment by imabari** [comment]
横375にサイズ調整しました。
文字が重なるので縦サイズを少し大きくしました。

サイズ指定ができないのでマウス操作で調整しております。
レスポンシブな方法があれば直します。

**Comment by kkd** [comment]
ありがとうございます。縦棒グラフの方がいいんですかね。
一旦クローズしますね。

**Comment by kkd** [comment]
ニュース追加。
@ 15714092fd8a56fb88f53e2380f3e2eb33de65cc
