### ISSUE TITLE
吉田の最新情報を反映したい(8/7)

### ISSUE THREAD

**Issue by kkd** [cheerup-ehime/cheerup-ehime.github.io#74]
## 誰のために？

吉田に向かうボラ向け

## 何を実現したい？

いくつかフィードバックがあったので反映したい。

![image](https://user-images.githubusercontent.com/37254/43819408-c6f8c0b4-9b1d-11e8-9dfa-ee093024bc49.png)

あとは、槇野さんの救援隊が大河内上まで到達している模様なので、それも地図に反映できるといい？
これは現場の人のフィードバックを聞いたほうが良さそう。。。。

## どうなったら完了？

- [x] 8/8時点のそのための情報収集
- [x] 8/8時点の状況反映

**Comment by kkd** [comment]
@imabari をを、私はIFTTTとZapierを使ってるのですが、こんなのもあったんですね。ちょっと調べてみます。

**Comment by kkd** [comment]
これ系で、ハッシュタグ決めて、ボラ募集や、告知系を集めたりすると良さそうです！

**Comment by imabari** [comment]
サンプルはストップしました。
無料だと月750回なので1時間に1回しか更新されません。

**Comment by imabari** [comment]
作り方記事にしておきました
https://imabari.hateblo.jp/entry/2018/08/10/115404
https://drive.google.com/open?id=1dfdZSntDgrkf0bljRvqeNIoBZSL5SlDv

**Comment by kkd** [comment]
このチケットは、 #75 でも対応しているので一旦クローズにします。

@imabari 
いつも、ありがとうございます。
可能であれば、チアのメンバーのIT開発担当として参加して頂いて
この辺りの設定なども是非やって頂けると助かります。
やり方わかってても、私一人だとどうしても作業が滞ってしまいますので。。。
