### ISSUE TITLE
立間の地図をよりわかりやすくしたい。

### ISSUE THREAD

**Issue by kkd** [cheerup-ehime/cheerup-ehime.github.io#75]
## 誰のために？

立間に自力でボラに来る人のため。

## 何を実現したい？

![立間の地図](https://cheerup-ehime.github.io/assets/images/maps/yoshida-tachima.png)

[吉田町の説明ページ](https://cheerup-ehime.github.io/volunteer-new/yoshida/)に掲載している、立間の地図についてFBのチームサクボでいくつかのFBをもらった。

ざっくりいうと**立間周辺のランドマークも記載して欲しい**とのこと。Googleにあるもの・ないものふくめ。

- [x] 立間駅の右側にも道があります。
- [ ] 立間駅の向かいには愛工房というみかんの工場がある小さな道路があります！(Googleにも掲載)
- [ ] 中之谷の向かいGoogleだとダイキがあるあたりから(高森)小名トンネルあたりまでも立間だそうです！
- [ ] ヤマトの営業所、ガソリンスタンドもあった方が良いと思います。
- [ ] 説明するときに吉田浄水場があると分かってもらえやすいです
- [ ] 中組、荒巻の集会所(Googleにはない)
  - ないので中組地区の南東側にある天満神社をマップに入れて集落までたどり着いてもらう感じになるかなぁと。
- [x] フリガナが欲しい。実は読めない地名が…(￣▽￣;)
- [ ] 案内用は別途にした方が良いかもです。中組、荒巻の集会所や車を停められる場所の案内が欲しい

## それはなぜ？

用途によって必要かどうかわかれる。

- Googleマップにはないものがある
- 土地に不案内な人がボラに来るときに使いたい
- ざっくり立間の状況を知りたい

## どうなったら完了？

まずは何をやるかやらないかを決めないと完了条件は決められない。。。
イラストマップとして提供するもの、地図アプリとして提供するものと分けて考えたほうがよさそう。

（みん地図に入れる/Googleマップに入れる）

**Comment by kkd** [comment]
関東愛媛県人会災害ボランティア部でこんな地図は作ってる。

**Comment by brightflavor** [comment]
@kkd FBページない見てました。
いろんな要望がまとめきれないまま錯綜してますね。目的が定まらないと完了地点も定まらない。
なんのための地図がほしいか、を聞いたほうが良いかもしれません。

**Comment by brightflavor** [comment]
@kkd あくまで個人的意見として。
サクボさんたちの視点がどうもボランティアに参加していただく方ではなく、自分たち（現地）に向いている気がします。

掲載されているページは「吉田町の現状を、地区・現場外の人に幅広くダイジェスト的に伝える」ことであるので、あくまで「地区の名称とざっくりとした位置」を確認できれば良いと思います。
ということで、公的なものに絞ったほうが良いと思います。

ということで

【位置追加】
・立間駅の右側の道
・中組・荒巻の集会所
・天満神社
・吉田浄水場（←というか、これは報道もされているのでこれは第一に対応したほうがいいかと）

【その他】
・ふりがな明記

を対応すればよいのでは、と考えています。

**Comment by brightflavor** [comment]
@kkd 
（すいません。書き直しました）
あくまで現状の意見を見ての個人的意見として。
サクボさんたちの視点がどうもボランティアに参加していただく方ではなく、自分たち（現地）に向いている気がします。

『立間に自力でボラに来る人のため」という視点から考えると…

【位置追加】
・立間駅の右側の道
・中組・荒巻の集会所
・天満神社
・吉田浄水場（←というか、これは報道もされているのでこれは第一に対応したほうがいいかと）
・愛工房（かなり大きい施設なので）

【その他】
・ふりがな明記

を対応すればよいのでは、と考えています。

駐車場については、複雑になってくるので別途用意になりますね。

**Comment by kkd** [comment]
@brightflavor 

とりあえず、公民館はGoogleマップとみん地図に入れたんで、そっちでマーカー増やしていけば充分な気がしています。

https://drive.google.com/open?id=1jgNBj6X4E3dKt2JInksbdlN05WjQMi_1&usp=sharing

具体的な利用シーンとして「チアのサイトの地図みて、ボラの人が現地のランドマークを確認しながら移動してくる」のかは正直疑問。地図アプリの方が実際の利用シーンに向いてる気がします。駐車場も地図アプリでいいと思います。

チアのサイトとして、この地図の目的を明確にしないといけませんね。
提案としては、

**立間周辺の地名と位置関係を理解するため**としたい。

上記だと

- 道
- 浄水場

くらいで充分では？他は地図にマッピングすればいいと思います。

**Comment by kkd** [comment]
立間駅周辺の地図だそうです。

![38731210_1917124315046939_1956960436347731968_n](https://user-images.githubusercontent.com/37254/43883938-b0bed27a-9bef-11e8-9bf4-e30ebbf094ad.jpg)

**Comment by kkd** [comment]
@yamada1231 @shokotakaichi 

地図に含める内容について、何かコメントございますか？

今の所、

- 掲載している立間マップには吉田浄水場、道、ふりがなを追加すればいい
- 細かいものはGoogleマップなどにマークして公開してあげればいい（地図起こさなくて不要）

という話をしていました。コメントいただければ。

**Comment by shokotakaichi** [comment]
私が作った地図は「愛媛のどこで」が視覚的にわかるような意図でしたのであれで現地には行けないでしょうね！
　
FBメッセージを見ましていつでもNAVIがすごくわかりやすいなと思いました。…と思ったのですがGoogleマップで対応できそうなんですね？
　
地図起こししているとどんどん細かい地図を作ることになるので、すごくいいですね。

現地の方の要望
・立間駅の右側の道
・中組・荒巻の集会所
・天満神社
・吉田浄水場
・愛工房
・ふりがな明記
　
が挙がっていますが、それ以外の書き加える点に関する追加の意見はありません。
　
ちなみにそれらのランドマークを追加したULRがあれば教えて頂きたいです＾＾

（私のパソコンではFBで懸田 さんがおっしゃっていたインポートや、googleマップのKMLのダウンロードができませんでしたので、googleマップにマークする作業はできそうにありません。）
　
確認なのですが、
・初参加のボランティアの方へ　①googleマップで目的地がマークされたもののURLを教える。→②初参加のボランティアの人はその地図を見て現地へ。→③現地で浄水場やその他の主要な場所について説明をうける（集会所など）。
という流れでいいでしょうか。

**Comment by yamada1231** [comment]
![-01](https://user-images.githubusercontent.com/41100143/43939308-17791458-9ca4-11e8-9a50-012aee070a15.png)


高市さんありがとうございます。
これ、多分私みたいに土地勘あったほうが早いので、こっちで修正しました。

**Comment by shokotakaichi** [comment]
んん゛？？
googleマップ上でマークするのかと思ったのですが＾＾
　
現地の人が説明するのに一枚の地図がとても扱いやすいとは思います。が、現地の人の要望では色々書き加えてほしいみたいでgoogleマップやいつでもNAVIを使用しようという流れだと…思っていたのですが…。
　
地名のふりがなすごいですね。自分が日本人か疑うぐらい読めませんね。

**Comment by shokotakaichi** [comment]
と思ったのですが過去のコメント見て理解しました、
**立間周辺の地名と位置関係を理解するため**
に「チアのマップ」を作る話だったんですね、すみません、誤読していました。
山田さんありがとうございます。

**Comment by yamada1231** [comment]
画像こっちで入れ替えました。

**Comment by kkd** [comment]
@yamada1231 @shokotakaichi 

立間駅周辺の手書き地図は、ほとんどがGoogleマップに情報があるのでいらないかな？
この部分だけ地図に起こしてもいいかもしれませんが、それほど意味があるとは思えませんね。

山田さんが対応してくれた、ふりがな対応、一部地名追加で完了としましょう。

ランドマークについては、グーグルマップで公開しているのと、別途「いつもNAVI」の紹介記事があるので問題ないと思います。
