### ISSUE TITLE
大洲のボラページのネットプリント情報を追加したい。

### ISSUE THREAD

**Issue by kkd** [cheerup-ehime/cheerup-ehime.github.io#78]
## 誰のために？

大洲に行くボランティア向け

## 何を実現したい？

申込用紙のネットプリントの設定したのですが、かき忘れてる。
ここの様式をネットプリント対応するところから。

http://www.ozushakyo.jp/cms/?p=1031

## どこを修正する？

- /volunteer-new/ozu.md

## どうなったら完了？
- [x] 個人登録の様式をネットプリント登録する（セブン）
- [x] 個人登録の様式をネットプリント登録する（セブン以外）
- [x] 団体登録の様式をネットプリント登録する（セブン）
- [x] 団体登録の様式をネットプリント登録する（セブン以外）
- [x] セブンイレブンのネットプリントの設定が記載されている
- [x] それ以外のコンビニのプリント設定が記載されている

**Comment by yamada1231** [comment]
これ、高速無料化の申請用紙ですよね？
宇和島も西予もそれぞれのページに記載されてないようなんですが。。。。

**Comment by kkd** [comment]
あ、大洲のボラ登録のPDFが入手できなかったんでした。。。（リストに入っていない）

大洲のボランティア活動証明申請は、大洲市社協の情報が書き込まれたPDFが用意されているので、それを登録すればよくて、その手順（コンビニプリント）は既にvolunteer_backup.mdに含めたのでした。なので記入しなくてよいですね（こちらの依頼ミスです。失礼しました。。。）

**Comment by kkd** [comment]
クローズします。。。

**Comment by kkd** [comment]
いや、ここに様式があったので追加します。
コンビニプリントの登録からやります。。。

http://www.ozushakyo.jp/cms/?p=1031

**Comment by kkd** [comment]
close at @ 022ef66263908e041eaa196442c2a74ded1832b6
